### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by AvidCoder101**
@aromalanil Sorry, for some reason, it made a new PR. I have made it to version 2.0.2

### CODE REVIEW

**Comment by aromalanil** [comment]
Sorry, 
Please give the changes to patch-1 branch. Or give a new PR with both change

**Comment by AvidCoder101** [comment]
Sorry, but where is patch-1?

**Comment by aromalanil** [comment]
It's the branch from which your first pr was made

**Comment by AvidCoder101** [comment]
So should I do it from my fork?

**Comment by aromalanil** [comment]
Yes. 
Create a branch in your fork (or push to patch-1), make the changes and give a PR from it.

**Comment by AvidCoder101** [comment]
It has been added to my other PR. Thanks for reviewing, I will close this PR.

**Pull request closed without merging**
